name: easy_google_maps
description: A new flutter plugin project.
version: 1.0.0+2
author: Rody Davis <rody.davis.jr@gmail.com>
repository: https://github.com/rodydavis/easy_google_maps
homepage: https://github.com/rodydavis/plugins
maintainer: Rody Davis (@rodydavis)
environment:
  sdk: ">=2.2.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  google_maps_flutter: ^1.2.0
  geolocator: ^7.0.0-nullsafety.5
  easy_web_view: ^1.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
