name: easy_google_maps
description: A new flutter plugin project.
version: 0.0.1
author:
homepage:

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  google_maps_flutter: ^0.5.21+12
  geolocator: ^5.1.5
  easy_web_view:
    git: git://github.com/rodydavis/easy_web_view

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
