name: easy_google_maps
description: Easy google maps plugin
version: 1.0.1-nullsafety
author: Rody Davis <rody.davis.jr@gmail.com>
repository: https://github.com/rodydavis/easy_google_maps
homepage: https://github.com/rodydavis/plugins
maintainer: Rody Davis (@rodydavis)
environment:
  sdk: ">=2.2.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  google_maps_flutter: ^1.2.0
  # geolocator: ^7.0.0-nullsafety.5
  # geocoding: ^1.0.1
  geolocator: ^5.3.2+2
  easy_web_view: ^1.4.0-nullsafety

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
